#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ColorfulBing.Resource", IsApplication=true)]

namespace ColorfulBing
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bing = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int location = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int gridLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int ivLocation = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int logoLayout = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int tvCalendar = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int tvCopyRight = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int tvDescription = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int tvLocation = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int SaveToDisk = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SetAsWallpaper = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int WaitDlgMsg = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int WaitDlgMsgSave = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int WaitDlgTitle = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
